Test CI/CD

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,21 +26,27 @@ jobs:
           channel: 'stable'
           architecture: x64
 
-      # Update the Kotlin Gradle plugin version
-      # - name: Update Kotlin Gradle plugin version
-      #   run: |
-      #     # Navigate to the build.gradle file for the :flutter_html_to_pdf project
-      #     cd flutter_html_to_pdf
-      #     # Use sed command to update the Kotlin Gradle plugin version
-      #     sed -i '' 's/org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50/org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31/' build.gradle
+      # Find flutter_html_to_pdf package path
       - name: Find flutter_html_to_pdf package path
         id: find-package-path
-        run: echo $(find . -type d -name "flutter_html_to_pdf")
-      # Use the output from the find command
+        run: echo "$(find . -type d -name "flutter_html_to_pdf")"
+        shell: /bin/bash
+        continue-on-error: false
+
+      # Update Kotlin Gradle plugin version
       - name: Update Kotlin Gradle plugin version
         run: |
-          cd ${{ steps.find-package-path.outputs.path }}
-          sed -i '' 's/org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50/org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31/' build.gradle
+          # Check if path is found and not empty
+          if [ -z "${{ steps.find-package-path.outputs.path }}" ]; then
+            echo "flutter_html_to_pdf path not found"
+            exit 1
+          else
+            # Navigate to the directory and update build.gradle
+            cd ${{ steps.find-package-path.outputs.path }}
+            sed -i '' 's/org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50/org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31/' build.gradle
+          fi
+        shell: /bin/bash
+
       # Proceed with the rest of the build process
       - run: flutter build apk --release --split-per-abi
       - run: |
